### ISSUE TITLE
Exposing argument expectations to return types

### ISSUE THREAD

**Issue by jamiehannaford** [phpspec/prophecy#179]
I have a piece of code I'd like to mock that is implemented like so:

```php
public function foo(array $args)
{
   return new Foo($args);
}
```

and I'm mocking it like so:

```php
$thing->foo(Argument::type('array'))->willReturn(new Foo([]));
```

is there any way to pass the arguments to `foo()` directly into the return object's constructor? I tried something like this:

```php
$thing->foo(Argument::type('array'))->will(function ($args) {
   $this->foo($args[0])->willReturn(new Foo($args[0]));
});
```

but I'm getting `NULL` returned when I call `foo()`. Is there an easier way?

**Comment by jamiehannaford** [comment]
Actually, extending `ReturnArgumentPromise` worked out quite nicely. Closing.

**Comment by stof** [comment]
I don't understand why you are doing ``$this->foo($args[0])->willReturn(new Foo($args[0]));``. this is changing the promise for **next** calls to ``foo($arrayPassedNow)``. and you get ``null`` because this is what your callback is returning.

The code doing this is much simpler:

```php
$thing->foo(Argument::type('array'))->will(function ($args) {
   return new Foo($args[0]);
});
```

However, if you want your mock to perform the real logic, why are you using a mock in the first place ?

**Comment by jamiehannaford** [comment]
@stof I ended up doing something similar to what you suggest. In answer to your other question, because subsequent logic was using the returned `Foo` object. I had other expectations/promises performing the required tests - the above problem was to do with just simulating an expected flow of execution.
