### ISSUE TITLE
Will return does not work when calling many times

### ISSUE THREAD

**Issue by lyrixx** [phpspec/prophecy#201]
Hello,

I hit a bug (or a feature I don't know):

Reproducer:

```
<?php

class Foobar
{
}

class Service
{
    public function process(Foobar $foobar)
    {

    }
}

class ServiceTest extends \PHPUnit_Framework_TestCase
{
    public function testProcess()
    {
        $f1 = new Foobar();
        $f2 = new Foobar();

        $s = $this->prophesize(Service::class);
        $s->process($f1)->willReturn(1)->shouldBeCalled();
        $s->process($f2)->willReturn(2)->shouldBeCalled();

        $service = $s->reveal();

        $this->assertSame(1, $service->process($f1));
        $this->assertSame(2, $service->process($f2));
    }
}
```

=>

```

PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

F

Time: 131 ms, Memory: 7.25Mb

There was 1 failure:

1) ServiceTest::testProcess
Failed asserting that 2 is identical to 1.
```

**Comment by everzet** [comment]
It's because default argument comparison is by-value, not by-identity. You `Foobar` is an empty class, which means that `$f1` is technically exactly the same as `$f2` when compared by value. You need to either start adding identity to your `Foobar` or switch to comparing by-identity with `Argument::is()`:

```php
$s->process(Argument::is($f1))->willReturn(1)->shouldBeCalled();
$s->process(Argument::is($f2))->willReturn(2)->shouldBeCalled();
```

Also, there is no point mixing stubs and mocks (`->willReturn(1)->shouldBeCalled()`). If your test is written right, it will fail anyways if stub is not used, as you can see in your own example.

**Comment by lyrixx** [comment]
Thanks for your fast reply. I checked in the documentation and I did not understand I could / should do that ;)

**Comment by lyrixx** [comment]
Actually, your solution does not work. I keep having the same result.

**Comment by everzet** [comment]
Yep, it seems to be a bug in how we compare arguments

**Comment by everzet** [comment]
For the time being if you add an instance variables to your `Foobar` and instantiate it with different values for two calls, this will solve the problem :/ While I'm working on a fix.

**Comment by lyrixx** [comment]
> For the time being if you add an instance variables to your Foobar

Yes, I did that in my code.
