### ISSUE TITLE
Argument::that not being called.

### ISSUE THREAD

**Issue by bweston92** [phpspec/prophecy#217]
```
$wasCalled = false;

$prophecized->method(Argument::that(function () use (&$wasCalled) {
  $wasCalled = true;
});

$prophecized->reveal()->method('');

$this->assertTrue($wasCalled);
```

The above will not work because Argument::that doesn't get invoked unless `shouldBeCalled` is called like the following.

```
$wasCalled = false;

$prophecized->method(Argument::that(function () use (&$wasCalled) {
  $wasCalled = true;
})->shouldBeCalled();

$prophecized->reveal()->method('');

$this->assertTrue($wasCalled);
```

**Comment by aik099** [comment]
But how call count for an expectation is collected if argument matchers are not evaluated?

**Comment by stof** [comment]
@bweston92 the issue is that you don't define anything for this method: no prediction (``->should*``) and no promise (``->will*``). So the matcher is not registered in the object in such case.
Not defining any behavior for a method does not make sense

**Comment by bweston92** [comment]
@stof makes sense, thanks!

**Comment by aik099** [comment]
Maybe an exception should be thrown later, when expectations are evaluated.

**Comment by stof** [comment]
This is because there is a special case in Prophecy: when none of the methods have a behavior defined, we consider it is a stub, and we allow calling any method on it, returning ``null``.

@everzet can you explain why such behavior was implemented initially ? I don't see any benefit for it actually, as returning ``null`` might be totally wrong (and in case of typed returns in PHP 7, it would be totally broken btw)
