### ISSUE TITLE
Unable to mock Composer\Composer

### ISSUE THREAD

**Issue by ddesrousseaux** [phpspec/prophecy#222]
I'm trying to mock Composer->getPackage() (and then ->getExtra()) but this sample test code doesn't work : 

``` php
class GeoipComposerScriptTest extends \PHPUnit_Framework_TestCase
{
        public function testSimple()
        {
            $composer = $this->prophesize('Composer\Composer');
            $composer->getPackage()->willReturn(true);
            $composer->reveal();
        }
}
```

I get this error message : 
**Prophecy\Exception\Doubler\MethodNotFoundException: Method `Double\stdClass\P1::getPackage()` is not defined**

The same test works with some others custom class name and methods. Any reason why it doesn't work with Composer? Is there any issue with classes coming from .phar files?

**Comment by aik099** [comment]
Have you tried replacing `\` with `\\`?

**Comment by ddesrousseaux** [comment]
Yes, I get the same error with Composer\\Composer

**Comment by zdenekdrahos** [comment]
Do you have access to `Composer\Composer` class? I get the same error, but I don't have Composer source code in repository. I guess that you don't have it too because of `stdClass` in error message.

This assertion fails in my case:

```php
$this->assertTrue(class_exists('Composer\Composer'));
```

When class is unknown then [method_exists] (http://php.net/manual/en/function.method-exists.php) probably returns `false` and [exception is thrown in prophecy](https://github.com/phpspec/prophecy/blob/4f9b1eaf0a7da77c362f8d91cbc68ab1f4718d62/src/Prophecy/Prophecy/MethodProphecy.php#L49).
