### ISSUE TITLE
Set default number of expected calls of shouldBeCalled at 1

### ISSUE THREAD

**Issue by theofidry** [phpspec/prophecy#227]
I see lots of usage of `::shouldBeCalled()` when using Prophecy, but except for some specific cases (I don't remember encountering one myself), you don't expect your method to be called more than _once_. This may lead to bugs and even if the number of calls doesn't cause any issue in itself, it's still a performance loss. My point is, it looks more _secure_ to have `::shouldBeCalled()` behaving as `::shouldBeCalledTimes(1)` and when the number of calls doesn't matter, to have to specify it explicitly. 

cc @jakzal

**Comment by stof** [comment]
Changing this would be a major BC break, so it is not posible

**Comment by theofidry** [comment]
Wouldn't it be possible to put it in a new major version and having a warning issue in the current version for example?

**Comment by aik099** [comment]
@theofidry , changing the default behavior to expect 1 instead of 1+ call would not only be a BC break (as @stof told), but also would violate core Prophecy principe - message bound expectations and not implementation bound expectations.

When by default you expect 1 call only, then a particular SUT is expected, but that shouldn't ever happen in message bound expectations.

**Comment by jakzal** [comment]
@aik099 If you consider Query/Command separation then it only makes sense to state expectations for commands (queries are stubbed). It doesn't matter how many time a query method is called. However, most of the time it actually matters that a command method was called once, as commands have side effects.

Having said that, I'm not convinced we should change behaviour at this point.
