### ISSUE TITLE
Add support for return type 'void'

### ISSUE THREAD

**Issue by psychomieze** [phpspec/prophecy#280]
With PHP 7.1 the return type 'void' is introduced. Prophecy currently fails with:

`Fatal error: A void function must not return a value`

when such a code is given:
`public` function foo(): `void`

As the Class double then contains:

<pre><code>
public function foo(): void
{
     return $this->getProphecy()->makeProphecyMethodCall(__FUNCTION__, func_get_args());
}
</code>
</pre>

**Comment by prolic** [comment]
This is urgent!

**Comment by FabianPiconeDev** [comment]
My method:
```
public function save(string $foo): void
{
    // ...
}
```
So what sould i "willReturn" here.. Without "willReturn" the method is not registered in the double.

`$this->myGateway->save(Argument::cetera());` <- dont works.

`$this->myGateway->save(Argument::cetera())->willReturn(???);` Does exists something like `willReturnTypeOf()`? Dont see anything about that in the docs...

**Comment by psychomieze** [comment]
@FabianPiconeDev Try simply adding an empty ->willReturn(); (that should be equivalent to null|void and register the method)

**Comment by FabianPiconeDev** [comment]
@psychomieze Already tried `$this->myGateway->save(Argument::cetera())->willReturn();`.
This will give me `Prophecy\Exception\Prophecy\MethodProphecyException: The method "save" has a void return type, and so cannot return anything`.

**Comment by stof** [comment]
well, I think that in your case, you should need to use something like `$this->myGateway->save(Argument::cetera())->shouldBeCalled()`.

A void function will never return something. So your test should care about it being called, as the fact of calling it is what is important.

**Comment by FabianPiconeDev** [comment]
So i have 7 test Methods in my test class. Depending on business logic, sometimes `save()` is being called and sometimes not. So i must add `$this->myGateway->save(Argument::cetera())->shouldBeCalled()` or `$this->myGateway->save(Argument::cetera())->shouldBeCalledTimes(0)`
in every Method, only that Prophecy does not crash.
On my other 6 test methods its not that what i want to test, i dont want to test that `save()` is being called there. According to the motto `test only one thing per testmethod`.

The problem is that the double does not know that `save()` exists because i can not specify it in setup-ing the testclass with something like `$this->myGateway->save(Argument::cetera())->isVoid()`. In my opinion it should exist an double method initialization like that.

Non specifying any method in the prophecy double will internally specify all methods. But when you specify a method by yourself, all other methods will not be specified. In my case i had to specify another method e.g. `getById()`. Now i have the salad, i cant specify a my `save()` method by myself that is type hinted as void. So i receive `Prophecy\Exception\Call\UnexpectedCallException: Method call: - save(..) on Double\MyGateway\P14 was not expected, expected calls were: - getById(..)`.
Yes i could create a new testclass where i only test `save()` but only due to a test framework limitation. It would be handy when Prophecy could initialize `void` method types in its doubles.

**Comment by stof** [comment]
> Depending on business logic, sometimes save() is being called and sometimes not

well, this sentence tells me that you should have multiple tests concerned about it being called or no, not only a single method (otherwise, you are not testing all your business logic).

A void-returning function generally has side effects (otherwise, it is useless). So the fact of being called is very important. If you don't care about calls in the 6 tests where it should not be called due to business logic, I could change the code of your class and always call save, and the test would stay green (while the business logic would be broken).

the motto `test only one thing per testmethod` means you should have separate tests for each of your business cases, not that you should have a single assertion for each of them.

**Comment by FabianPiconeDev** [comment]
@stof Allright you convinced me to add the assertion in every needed method. Thanks.

**Comment by vancouverwill** [comment]
This still seems to be an issue if you use `Argument::that()`
```
$this->myGateway->save(Argument::that(function($saveObject) {
           return $saveObject !== null;
})->shouldBeCalled()
```

You will get an error stating that expected first parameter should be a callback but was actually the value of `$instanceObject`.

I get around this by removing the void return type on the argument I am trying to test like `save()` and calling the below which still runs the callback. Which is okay but as @psychomieze said prevents utilisation of the `void` return type
```
$this->myGateway->save(Argument::that(function($saveObject) {
           return $saveObject !== null;
})->willReturn(null)
```

**Comment by andersoncontreira** [comment]
In my case I use this solution for this case, I don't know if it is the best solution, but I hope that can be helpful to others if the same question like I was before try to find something.

`

	//Mock

	$repository = $this->prophesize(FreightSubsidyRuleRepositoryInterface::class);
	$repository->insert(Argument::type(FreightSubsidyRule::class))->will(function($args){return $args[0];});
	$repository->beginTransaction()->will(function(){});
	$repository->commit()->will(function(){});
	$repository->rollback()->will(function(){});
`
