### ISSUE TITLE
String comparison issue in multidimensional array

### ISSUE THREAD

**Issue by BobMali** [phpspec/prophecy#409]
I have a controller using a service which gets an array as parameter. Whilst testing the controller i mock the used service and try to test for a single entry within the parameter-array passed to the service-mock.
If the parameter-array is a simple associative array the test works. If it is a multidimensional array it fails with the error-message `strpos() expects parameter 1 to be string, array given`.

Here is a stripped-down example of the controller:
```php
<?php
declare(strict_types=1);

class FakeController
{
    public function bar(FakeService $fakeService): bool
    {
        return $fakeService->getFakeData(
            [
                'foo' => 'bar baz',
                'bar' => 'sef baz',
                'baz' => [
                    [
                        'foobar' => 'bar foo'
                    ]
                ]
            ]
        );
    }
}
```

Here is the skeleton of the fake-service:
```php
<?php
declare(strict_types=1);

class FakeService
{
    public function getFakeData(array $inputArray): void
    {
        return true;
    }
}
```
Here is the failing test-class:
```php
<?php
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Prophecy\Argument;

class FakeControllerTest extends TestCase
{
    /**
     * @test
     */
    public function barShouldReturnArrayContainingFooFieldWithString(): void
    {
        $subject = new FakeController();
        $fakeServiceMock = $this->prophesize(FakeService::class);

        $fakeServiceMock->getFakeData(
            Argument::withEntry('foo', Argument::containingString('bar'))
        )
            ->shouldBeCalled();

        $subject->bar($fakeServiceMock->reveal());
    }
}
```
If the array is reverted to a simple associative array (remove array-index 'baz') the test is succeding.

**php-version**: 7.1
**phpunit-version**: ~6.5

Where did i go wrong?

**Comment by avant1** [comment]
As I understand the code you provided is not actual failing code.

You have duplicate key `bar` in `getFakeData()` call. 
So my guess is that you have same `bar` key instead of `foo` here:
```php
Argument::withEntry('foo', Argument::containingString('bar'))
```

This combination will lead to `strpos() expects parameter 1 to be string, array given` error because `bar` key will be array (second key overwrites first one).

Please double check array keys.

**Comment by DonCallisto** [comment]
Theoritetically there is an "issue" only because the search goes on even onto the "wrong" key. 
BTW if `foo` is an array itself, that would be the right behaviour.

What would you expect here? To have a "`false` score" returned or "`true` score" from this `Argument`?
If the latter, you're not using it the right way.
In the first case, actually, this seems not to be the correct behaviour as I would expect to have "`false` score"

**Comment by BobMali** [comment]
Yes, if `foo` were an array this would not have surprised me. But it is not.

My goal with this test was to test that the provided parameter-array contains the entry `foo` with a value which contains the string `bar`. So i guess i was expecting a "`true` score". Could you tell me how i should have used it instead?

**Comment by BobMali** [comment]
Has really no one else run into this problem before?
